sudo: true
language: php
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - mysql
  - redis-server

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - bash ci/sync-gitee.sh
  - mkdir build
  - phpenv config-rm xdebug.ini
  - bash ci/install.sh
  - echo $(php -r "echo SWOOLE_VERSION;")

install:
  - composer install

before_script:
  - bash ci/init-mysql.sh

script:
  - php tests/run.php -c phpunit.xml

after_success:
  - bash ci/deploy-www.sh

env:
  global:
    - secure: "ueDy3FFkSij8aQ6s3LLBFjpBFnQYoYNZHWqofSp8YIwSUMtU1HLkCltnYRZh5vU9o9lXOP+p5Pv/hbXhnEsee74G7ebhWog6J3w5GlmnbHBbhdyBa1nqGiDSWp4isLPOhq+G+nyMl24kzUUVnjhqOk3+mP6pPbC0RRzs8bqCzCP+n7ZCBiuE4Yu88Q7oN34FczDyViDCuss1A5VbTp8yjSs+435XDIkYqd8VKqC0a5GdbvTWAUIOiyNjxABWyAFWJ+HVEBFVg+AsB2bSHmBNn5hsbilmyr1HHsar8agZiaEOa6kZXpN4fVr1MKAW1YUj3xKosGBUdDQ3gktI3YlPGRuh6zd8QOSSnwYboP5IRvUOMxkoa/kVaFrrklHZs2Jh7Uu/MDHSrWHKCNvwcBiJavA5Lv/+NM0Cwfstr6pY+EVLyFSP0cHpyVzZPlo/Jp6JMWFowcrUHYYyZKgEHvXC16rZA7rlEuLpwQFzoew/1bF1uPrYp+JAmXRBhHPwQb+7bykHIheb9kGYutgqtm5oYD647CQ1xqIXLiE75xQBDcshD2fetWaDzyNWMQG1814+BBSiUm2OqapykW4peA4soif/u4B7kWIsrU11pBU8n162QoxK1c+x6I+sHue6VH2XSZoKFKnr07VwGFFwzuRlWSqEZiZTPO6R2sf6oAnDwGM="
    - secure: "g7K4D9VCaUYayUOqkuMzd/+P21zdXDgG2ES5fcWjyakuluZsxBt7fwL+s73A45aCwiYlYEUftLPFTkfIcGDu92oqG4nXS/XACjPFAF+rv/Qne5yH446NtHfKmu4og86mR4BIQALx+qrX/TYtmOnlD8JqVE7opJ7a1mg1NwM0bCpinc1+e9fIDqsvXCuZyceVbyzLohTa2bg2POrAOgDHwdcC+W+x0bC5QTdV+AmPwD0dKCwQg1SIRRwrgmNYEc9KnGE/dFMTUhZRVZXyqdv2ZxSWa7/mEB9YnjrFx3kA3PZGrg8Ez+bkRHzao3AkK/rEJfAwS8/wOsnqaUpzCJodJsMbJHjU+NIJYnag74Kmx+Evpp90KFdfKMesN9Ao62vepY0g3O0ed0XXrCsQaOyZHxTJzCG+3liyyBylavNFFoat5zQsJQJyAslmDZf+Hl6ohIeoBtsluedXJknAHijYJpdILwzHaBkAj06FnQH/aGi2ow8BbrAN8rWVOgKqmRWfhDuAWPawbBcK0sdlgtO0JmDzdCuS/LumBUIPrEWF+HbhCsVwdQUjugpa2zbzN3xhFqxA8DsjdexOt+iUfZrWHTHbR07M6IK7MDzyauDQY0LWRjKedYSMoBmS0wcKrJQiLsy3xN6pJEANIQN60pL7dZWZTU5KkTTO89U6xXVzgSM="
    secure: "T1cO/HfQw2L5tHP3RH9PQQqRB0dYVO7cpEsv3gjuO235SbpGVbIfeyss6OLJcgH8K9MVy6cKAUIEQJTdTJnhgCb0y39HKzUCMYk2WeQ1IOQd/GPktFn90O9wl2ixdASUpHBVMK2WjgoSg1f/4gzLtmvf7FLw6RHSgelRkoYY+7nHtPsLozb0fn6vDE+nhFU90haJeM0pLDHvYqSgDKELh3bXWEsudrsH36nf5D5f4KHh61Hz6Vu+YnvTCgKXRxLuZ62a7PmCCIysKRTFR7ok2Ol5O2urRLnKieZ19fT19up7A5a2XbPS/+5pK6VaobndQy7YKxtHh341cSv9HufoYoriMoBTh3EbcfPkKve56eB6hreHED3IYLLJAjdQibugDHAFxyHBlxoKKK2MfXL4tzWoolQ1hHzn/aSBoBbX/1UGmsPDY8RdAKq5aRwhWj97zqjk+rAUHzuIlITB3jHpMaZlwih+Dq7rQkZilnNbN5Mp3HwSlCaA9X7W9zIHi+7V2P8Hu9HCVNjtAG5ItSd63qMeqTfgCTx6fYEvMEc1JnO6LlDZy22nLnQ+44EVw2TNtwbs04al0nhhSaklTac++hQIWFtMXlISspd02FXbxEAI4NIRD4XvegLLpdOONFYmh4+CmOyd9hCm4PzioK/GEaCMuT0SQZXH7gdxRU1yktU="