sudo: true
language: php
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - mysql
  - redis-server

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - bash ci/install.sh

install:
  - composer install

before_script:
  - bash ci/init-mysql.sh

script:
  - php tests/run.php -c phpunit.xml
