sudo: false
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install

script:
  - mkdir -p build/coverage
  - composer test

after_success:
  - composer require --dev php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls